const ACTIONS = {
  SET_DIALOG: "SET_DIALOG",
  ADD_ITEM_TO_BASKET: "ADD_ITEM_TO_BASKET",
  REMOVE_ITEM_FROM_BASKET: "REMOVE_ITEM_FROM_BASKET",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  SET_SIDEBAR_FILTER: "SET_SIDEBAR_FILTER",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export default ACTIONS;
